#-------------------------------
# Site Settings
title: Cloud BLOG
logo: # You can add own logo. For example '/images/logo.png'.
description: Personal website and blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhang-wentao.tech" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Tags"
      url: "/tags/"
    - title: "Contact"
      url: "/contact/"
    - title: "RSS"
      url: "/feed.xml"

#-------------------------------
# Contact Settings
contact:
  form_id: https://formspree.io/f/mgerdblk # Add your form_id
  description: # Menca comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: demo-menca # Add your shortname for Disqus Comment. For example demo-menca